### ISSUE TITLE
"Not enough acceleration"

### ISSUE THREAD

**Issue by aryaman-patel** [kevin-robb/eece5554-vslam#2]
Hey Robb! 
I am trying to implement ORB SLAM 3 on the same Nuance car data-set. I was wondering if you tried to implement Stereo-Inertial? If yes, did you face any issues like "not enough acceleration" / or initialization of frames ?

**Comment by kevin-robb** [comment]
We did not attempt stereo+inertial. We had issues getting stereo to work, but these mostly seemed like incompatibilities with the compilation & setup rather than the algorithm itself. The particular issue you mention sounds like it relates to the IMU component, and it's not something I recall seeing.

My advice if you wish to do stereo+inertial ORB SLAM is to first use a dataset such as one of their provided ones to make sure your setup is working before attempting it with the NUance data. The next debugging step could involve making a script to analyze just your IMU data to make sure it looks reasonable when compared to IMU data from other car-based datasets.

Best of luck getting your implementation working.

**Comment by aryaman-patel** [comment]
Thanks for the reply!
Yes, my system seems to be working well with the example data sets. I have tested for EuRoC Monocular-inertial and Stereo-Inertial, both working well. 
I also have been able to implement it on the NUance data correctly! 
The issue it seems is that there is not enough IMU excitation in the NUance data-set for the ORB SLAM algorithm to perform IMU initialization, and its evident from the EuRoC example (the drone is jumping up and down in the beginning!).
What would you suggest?

**Comment by kevin-robb** [comment]
I'm glad to hear you've gotten it working on the testing sets at least! If you've accumulated your setup steps somewhere I'd love to check it out and try again for myself, since we never did get stereo or inertial working.

That's an interesting problem; I can't imagine the algorithm relies heavily on intense motions like the drone, since most platforms aren't capable of that behavior. If there are any parameters you can tune, perhaps the acceleration is being thresholded to some value that's simply set higher than you can expect from a car. I'd recommend checking out all the configurable parameters and seeing if you can get the error to go away. If this doesn't work, you could look for the line in the source code that produces the error you're seeing, and do some analysis around it to diagnose exactly what is happening.
